# Generated by Django 3.2 on 2024-12-22 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_sensordata_illuminance'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='年月日')),
                ('result', models.CharField(choices=[('win', '勝ち'), ('loss', '負け'), ('draw', '引き分け')], max_length=10, verbose_name='勝敗')),
                ('video_url', models.URLField(verbose_name='動画URL')),
                ('notes', models.TextField(blank=True, verbose_name='補足')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='video_posts')),
            ],
        ),
    ]
