# Generated by Django 3.2 on 2025-01-04 17:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='character',
            field=models.CharField(default='不明', max_length=30, verbose_name='使用キャラ'),
        ),
        migrations.AddField(
            model_name='videopost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 4, 17, 7, 31, 880564, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videopost',
            name='title',
            field=models.CharField(default='新しい動画', max_length=200, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='notes',
            field=models.TextField(blank=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='result',
            field=models.CharField(choices=[('win', '勝ち'), ('loss', '負け'), ('draw', '引き分け'), ('unknown', '不明')], max_length=10, verbose_name='勝敗'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
