# Generated by Django 3.2 on 2025-09-23 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_sensordata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('task_type', models.CharField(choices=[('one_time', '一時'), ('recurring', '定期')], max_length=10, verbose_name='タスクタイプ')),
                ('frequency', models.CharField(blank=True, choices=[('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月')], max_length=10, null=True, verbose_name='頻度')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10, verbose_name='優先度')),
                ('status', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '実施中'), ('completed', '終了済み')], default='not_started', max_length=15, verbose_name='ステータス')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='期限')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
