# Generated by Django 3.2 on 2025-09-23 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('frequency', models.CharField(choices=[('one_time', '一時'), ('recurring', '定期')], max_length=10, verbose_name='頻度')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='金額')),
                ('remaining_count', models.IntegerField(default=0, verbose_name='残数')),
                ('status', models.CharField(choices=[('insufficient', '不足'), ('available', '残あり')], default='insufficient', max_length=15, verbose_name='ステータス')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('memo_type', models.CharField(choices=[('note', 'ノート'), ('idea', 'アイデア'), ('todo', 'TODO'), ('reference', '参考資料'), ('reminder', 'リマインダー'), ('other', 'その他')], max_length=20, verbose_name='種別')),
                ('content', models.TextField(verbose_name='詳細')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='お気に入り')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_favorite', '-updated_date'],
            },
        ),
    ]
