# Generated by Django 3.2 on 2025-10-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_memo_shoppingitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['status', 'remaining_count', '-updated_date']},
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='threshold_count',
            field=models.IntegerField(default=0, verbose_name='不足数'),
        ),
    ]
