# Generated by Django 3.2 on 2025-11-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20251102_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', '未着手'), ('in_progress', '実施中'), ('completed', '完了')], default='not_started', max_length=15, verbose_name='ステータス'),
        ),
    ]
