# Generated by Django 3.2 on 2025-11-03 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='ラベル名')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'タスクラベル',
                'verbose_name_plural': 'タスクラベル',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='app.tasklabel', verbose_name='ラベル'),
        ),
    ]
