# Generated by Django 3.2 on 2025-11-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20251103_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='task',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='終日'),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了日時'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='app.task', verbose_name='親タスク'),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='繰り返し回数'),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_interval',
            field=models.IntegerField(default=1, verbose_name='繰り返し間隔'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始日時'),
        ),
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(blank=True, choices=[('', '---'), ('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月'), ('yearly', '毎年')], default='', max_length=10, verbose_name='頻度'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='優先度'),
        ),
        migrations.AlterField(
            model_name='tasklabel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='ラベル名'),
        ),
    ]
