# Generated by Django 3.2 on 2025-11-04 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_memo_types(apps, schema_editor):
    MemoType = apps.get_model('app', 'MemoType')
    Memo = apps.get_model('app', 'Memo')

    defaults = {
        'メモ': '#007bff',
        'アイデア': '#28a745',
        'その他': '#6c757d',
    }
    created_types = {}
    for name, color in defaults.items():
        memo_type, _ = MemoType.objects.get_or_create(user=None, name=name, defaults={'color': color})
        created_types[name] = memo_type

    mapping = {
        'note': created_types['メモ'],
        'idea': created_types['アイデア'],
    }
    # For remaining legacy codes, fall back to "その他"
    fallback = created_types['その他']

    for memo in Memo.objects.all():
        legacy_value = getattr(memo, 'memo_type', '')
        memo.memo_type_fk = mapping.get(legacy_value, fallback)
        memo.save(update_fields=['memo_type_fk'])


def noop_reverse(apps, schema_editor):
    # No-op reverse migration
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20251104_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memo_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='memo',
            name='memo_type_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memos', to='app.memotype', verbose_name='種別'),
        ),
        migrations.RunPython(create_default_memo_types, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name='memo',
            name='memo_type',
        ),
        migrations.RenameField(
            model_name='memo',
            old_name='memo_type_fk',
            new_name='memo_type',
        ),
        migrations.AlterField(
            model_name='memo',
            name='memo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memos', to='app.memotype', verbose_name='種別'),
        ),
    ]
