# Generated by Django 3.2 on 2025-11-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_memotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memotype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
