# Generated by Django 3.2 on 2025-11-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_memotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(blank=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='memotype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
