# Generated by Django 3.2 on 2025-11-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_memotype_id'),
        ('app', '0017_alter_memotype_name_alter_memo_content'),
    ]

    operations = [
    ]
