# Generated by Django 3.2 on 2026-02-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20251122_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.RemoveField(
            model_name='videopost',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='VideoPost',
        ),
    ]
