# Generated by Django 3.2 on 2026-02-09 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_remove_sensordata_videopost_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('expense', '支出'), ('income', '収入'), ('no_change', '変動なし')], default='expense', max_length=10)),
                ('major_category', models.CharField(choices=[('variable', '変動費'), ('fixed', '固定費'), ('special', '特別費')], default='fixed', max_length=10)),
                ('purpose_description', models.TextField(blank=True, default='')),
                ('frequency', models.CharField(choices=[('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月'), ('yearly', '毎年')], max_length=10)),
                ('day_of_week', models.IntegerField(blank=True, help_text='曜日（0=月曜, 6=日曜）。毎週の場合に使用。', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='日（1-31）。毎月・毎年の場合に使用。', null=True)),
                ('month_of_year', models.IntegerField(blank=True, help_text='月（1-12）。毎年の場合に使用。', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_executed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
