# Generated by Django 3.2 on 2026-02-09 16:59

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_recurringpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringpayment',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='days_of_month',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='日リスト（1-31）。毎月・毎年の場合に使用。最大7つ。', size=None, validators=[django.core.validators.MaxLengthValidator(7)]),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='days_of_week',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='曜日リスト（0=月曜, 6=日曜）。毎週の場合に使用。最大7つ。', size=None, validators=[django.core.validators.MaxLengthValidator(7)]),
        ),
    ]
