# Generated by Django 5.2 on 2026-03-03 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20260210_0159'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='習慣名')),
                ('frequency', models.CharField(choices=[('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月')], default='daily', max_length=10, verbose_name='頻度')),
                ('coefficient', models.FloatField(default=1.0, verbose_name='係数')),
                ('color', models.CharField(default='#4CAF50', max_length=7, verbose_name='色')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '習慣',
                'verbose_name_plural': '習慣',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.habit')),
            ],
            options={
                'verbose_name': '習慣記録',
                'verbose_name_plural': '習慣記録',
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
