# Generated by Django 5.2 on 2026-03-03 06:07

from django.db import migrations, models


def migrate_coefficient(apps: object, schema_editor: object) -> None:
    """FloatField の coefficient をマイナス/プラスに分離する。
    マイナス値は is_positive=False にして絶対値を保存する。
    0 以上 1 未満の値は 1 に切り上げる。
    """
    Habit = apps.get_model('app', 'Habit')  # type: ignore[attr-defined]
    for habit in Habit.objects.all():
        coeff = float(habit.coefficient)
        if coeff < 0:
            habit.is_positive = False
            coeff = -coeff
        else:
            habit.is_positive = True
        # 整数に丸め、最低 1
        habit.coefficient = max(1, round(coeff))
        habit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_habit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='color',
        ),
        migrations.AddField(
            model_name='habit',
            name='is_positive',
            field=models.BooleanField(default=True, verbose_name='良い習慣'),
        ),
        migrations.AddField(
            model_name='habit',
            name='monthly_goal',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='月の目標回数'),
        ),
        migrations.AddField(
            model_name='habit',
            name='weekly_goal',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='週の目標回数'),
        ),
        # データ移行: マイナス係数 → is_positive=False + 絶対値
        migrations.RunPython(migrate_coefficient, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='habit',
            name='coefficient',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='係数'),
        ),
    ]
