# Generated by Django 5.2 on 2026-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_habit_record_v2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['-status', 'remaining_count', '-updated_date']},
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='購入済み'),
        ),
    ]
