# Generated by Django 5.2 on 2026-03-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_temptaskitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='chart_color',
            field=models.CharField(blank=True, default='', help_text='グラフ表示色（例: #FF6B6B）', max_length=7),
        ),
    ]
