# Generated by Django 5.2 on 2026-03-22 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_category_chart_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempTaskSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='セット名')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_task_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '一時タスクセット',
                'verbose_name_plural': '一時タスクセット',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='temptaskitem',
            name='task_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.temptaskset', verbose_name='セット'),
        ),
    ]
