# Generated by Django 5.2 on 2026-03-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_temptaskset'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='admin_reply',
            field=models.TextField(blank=True, verbose_name='管理者返信'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='返信日時'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('open', '未対応'), ('in_progress', '対応中'), ('resolved', '対応済み')], default='open', max_length=20, verbose_name='ステータス'),
        ),
    ]
