# Generated by Django 5.2 on 2026-03-29 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_admin_panel_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('expenses', '家計簿'), ('tasks', 'タスク'), ('memos', 'メモ'), ('shopping', '買うものリスト'), ('habits', '習慣トラッカー')], max_length=20, verbose_name='機能')),
                ('action', models.CharField(choices=[('view', '閲覧'), ('create', '追加'), ('edit', '編集'), ('delete', '削除'), ('toggle', '切替')], max_length=20, verbose_name='操作')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アクティビティログ',
                'verbose_name_plural': 'アクティビティログ',
                'ordering': ['-accessed_at'],
                'indexes': [models.Index(fields=['page', 'action', 'accessed_at'], name='app_activit_page_68747d_idx')],
            },
        ),
    ]
