# Generated by Django 5.2 on 2026-03-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='page',
            field=models.CharField(choices=[('expenses', '家計簿'), ('tasks', 'タスク'), ('memos', 'メモ'), ('shopping', '買うものリスト'), ('habits', '習慣トラッカー'), ('demo', 'デモ')], max_length=20, verbose_name='機能'),
        ),
    ]
