# Generated by Django 5.2 on 2026-07-08 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_calendartoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カレンダー名')),
                ('url', models.URLField(max_length=500, verbose_name='ICS URL')),
                ('color', models.CharField(default='#6c8ebf', max_length=7, verbose_name='色')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最終同期日時')),
                ('last_error', models.CharField(blank=True, default='', max_length=200, verbose_name='最終同期エラー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_calendars', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '外部カレンダー',
                'verbose_name_plural': '外部カレンダー',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='', max_length=500, verbose_name='UID')),
                ('title', models.CharField(max_length=300, verbose_name='タイトル')),
                ('start_date', models.DateTimeField(verbose_name='開始日時')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('all_day', models.BooleanField(default=False, verbose_name='終日')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.externalcalendar', verbose_name='外部カレンダー')),
            ],
            options={
                'verbose_name': '外部イベント',
                'verbose_name_plural': '外部イベント',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='externalcalendar',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='unique_external_calendar_url_per_user'),
        ),
        migrations.AddIndex(
            model_name='externalevent',
            index=models.Index(fields=['calendar', 'start_date'], name='app_externa_calenda_b5fd9b_idx'),
        ),
    ]
