# Generated by Django 5.2 on 2026-07-25

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_budget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_type", models.CharField(max_length=40, verbose_name="データ種別")),
                ("object_label", models.CharField(max_length=40, verbose_name="表示種別")),
                ("object_name", models.CharField(max_length=200, verbose_name="表示名")),
                (
                    "payload",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        verbose_name="復元データ",
                    ),
                ),
                ("deleted_at", models.DateTimeField(auto_now_add=True, verbose_name="削除日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "削除済みデータ",
                "verbose_name_plural": "削除済みデータ",
                "ordering": ["-deleted_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "deleted_at"],
                        name="app_del_user_date_idx",
                    ),
                ],
            },
        ),
    ]
