# Generated by Django 5.2 on 2026-07-26

import app.cooking.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0035_deleteditem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CookingDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="料理名")),
                ("ingredients", models.TextField(blank=True, verbose_name="材料リスト")),
                (
                    "recipe_mode",
                    models.CharField(
                        choices=[("single", "一括メモ"), ("steps", "手順ごと")],
                        default="single",
                        max_length=10,
                        verbose_name="レシピ形式",
                    ),
                ),
                ("recipe_text", models.TextField(blank=True, verbose_name="レシピ")),
                (
                    "servings",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="分量（人分）",
                    ),
                ),
                (
                    "cooking_time_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                        verbose_name="所要時間（分）",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="メモ")),
                ("is_favorite", models.BooleanField(default=False, verbose_name="お気に入り")),
                (
                    "photo_1",
                    models.FileField(
                        blank=True,
                        upload_to=app.cooking.models.cooking_image_upload_to,
                        validators=[app.cooking.models.validate_cooking_image],
                        verbose_name="料理写真1",
                    ),
                ),
                (
                    "photo_2",
                    models.FileField(
                        blank=True,
                        upload_to=app.cooking.models.cooking_image_upload_to,
                        validators=[app.cooking.models.validate_cooking_image],
                        verbose_name="料理写真2",
                    ),
                ),
                (
                    "photo_3",
                    models.FileField(
                        blank=True,
                        upload_to=app.cooking.models.cooking_image_upload_to,
                        validators=[app.cooking.models.validate_cooking_image],
                        verbose_name="料理写真3",
                    ),
                ),
                (
                    "photo_4",
                    models.FileField(
                        blank=True,
                        upload_to=app.cooking.models.cooking_image_upload_to,
                        validators=[app.cooking.models.validate_cooking_image],
                        verbose_name="料理写真4",
                    ),
                ),
                (
                    "photo_5",
                    models.FileField(
                        blank=True,
                        upload_to=app.cooking.models.cooking_image_upload_to,
                        validators=[app.cooking.models.validate_cooking_image],
                        verbose_name="料理写真5",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="登録日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooking_dishes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "料理",
                "verbose_name_plural": "料理",
                "ordering": ["-is_favorite", "-updated_at", "-pk"],
                "indexes": [
                    models.Index(fields=["user", "updated_at"], name="cook_user_updated_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CookingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="手順番号",
                    ),
                ),
                ("instruction", models.TextField(verbose_name="手順")),
                (
                    "photo_1",
                    models.FileField(
                        blank=True,
                        upload_to=app.cooking.models.cooking_image_upload_to,
                        validators=[app.cooking.models.validate_cooking_image],
                        verbose_name="手順写真1",
                    ),
                ),
                (
                    "photo_2",
                    models.FileField(
                        blank=True,
                        upload_to=app.cooking.models.cooking_image_upload_to,
                        validators=[app.cooking.models.validate_cooking_image],
                        verbose_name="手順写真2",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="app.cookingdish",
                        verbose_name="料理",
                    ),
                ),
            ],
            options={
                "verbose_name": "料理手順",
                "verbose_name_plural": "料理手順",
                "ordering": ["position", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1), ("position__lte", 10)),
                        name="cooking_step_position_1_10",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cooked_on", models.DateField(verbose_name="作った日")),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                        verbose_name="回数",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200, verbose_name="メモ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="登録日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="app.cookingdish",
                        verbose_name="料理",
                    ),
                ),
            ],
            options={
                "verbose_name": "料理作成履歴",
                "verbose_name_plural": "料理作成履歴",
                "ordering": ["-cooked_on", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dish", "cooked_on"), name="unique_cooking_day"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("count__gte", 1), ("count__lte", 999)),
                        name="cooking_history_count_1_999",
                    ),
                ],
            },
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="page",
            field=models.CharField(
                choices=[
                    ("expenses", "家計簿"),
                    ("tasks", "タスク"),
                    ("memos", "メモ"),
                    ("shopping", "買うものリスト"),
                    ("habits", "習慣トラッカー"),
                    ("cooking", "料理記録"),
                    ("demo", "デモ"),
                ],
                max_length=20,
                verbose_name="機能",
            ),
        ),
    ]
