# Generated by Django 5.2 on 2026-07-26 06:15

from django.conf import settings
from django.db import migrations, models


def backfill_sort_order(apps, schema_editor):
    """既存データの作成順（PK順）をユーザーごとの表示順にする。"""
    for model_name in ("Category", "PaymentMethod", "TaskLabel"):
        model = apps.get_model("app", model_name)
        counters = {}
        instances = []
        for instance in model.objects.order_by("user_id", "pk"):
            counters[instance.user_id] = counters.get(instance.user_id, 0) + 1
            instance.sort_order = counters[instance.user_id]
            instances.append(instance)
        if instances:
            model.objects.bulk_update(instances, ["sort_order"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_cookingdish_cookingstep_cookinghistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['sort_order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='tasklabel',
            options={'ordering': ['sort_order', 'pk'], 'verbose_name': 'タスクラベル', 'verbose_name_plural': 'タスクラベル'},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='tasklabel',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='既定のラベル'),
        ),
        migrations.AddField(
            model_name='tasklabel',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.RunPython(backfill_sort_order, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='tasklabel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_task_label_per_user'),
        ),
    ]
