# Generated by Django 3.2 on 2025-11-16 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_count',
            field=models.IntegerField(default=0, verbose_name='アクセス数'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='メールアドレス認証済み'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン日時'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='login_attempt_count',
            field=models.IntegerField(default=0, verbose_name='ログイン試行回数'),
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='アクセス元地域')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ログイン日時')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ログイン履歴',
                'verbose_name_plural': 'ログイン履歴',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='トークン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('is_verified', models.BooleanField(default=False, verbose_name='検証済み')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'メール認証トークン',
                'verbose_name_plural': 'メール認証トークン',
                'ordering': ['-created_at'],
            },
        ),
    ]
