# Generated by Django 5.2 on 2026-03-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20251116_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終アクティブ日時'),
        ),
    ]
