# Generated by Django 5.2 on 2026-07-05 12:56

import auth_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_admin_panel_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'アカウントグループ',
                'verbose_name_plural': 'アカウントグループ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, upload_to='account_avatars/', validators=[auth_app.models.validate_avatar_file], verbose_name='アカウントアイコン'),
        ),
        migrations.CreateModel(
            name='AccountMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_memberships', to=settings.AUTH_USER_MODEL, verbose_name='追加したユーザー')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='auth_app.accountgroup', verbose_name='アカウントグループ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_membership', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アカウント所属',
                'verbose_name_plural': 'アカウント所属',
                'ordering': ['created_at'],
            },
        ),
    ]
