# Generated by Django 5.2 on 2026-07-05 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_accountgroup_customuser_avatar_accountmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='auth_app.accountgroup', verbose_name='子グループ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_group_links', to=settings.AUTH_USER_MODEL, verbose_name='作成したユーザー')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='auth_app.accountgroup', verbose_name='親グループ')),
            ],
            options={
                'verbose_name': 'アカウントグループ連携',
                'verbose_name_plural': 'アカウントグループ連携',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'child'), name='unique_account_group_link'), models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='account_group_link_not_self')],
            },
        ),
    ]
