# Generated by Django 5.2 on 2026-07-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_accountgrouplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_reset_email_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='パスワードリセットメール最終送信日時'),
        ),
    ]
