# Generated by Django 5.2 on 2026-08-23 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_customuser_last_password_reset_email_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityReportDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True, verbose_name='レポート日')),
                ('status', models.CharField(choices=[('sending', '送信中'), ('sent', '送信済み'), ('failed', '送信失敗')], default='sending', max_length=10, verbose_name='送信状態')),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最終送信試行日時')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信完了日時')),
                ('security_event_count', models.PositiveIntegerField(default=0, verbose_name='セキュリティイベント件数')),
                ('critical_error_count', models.PositiveIntegerField(default=0, verbose_name='重大エラー件数')),
            ],
            options={
                'verbose_name': 'セキュリティレポート送信履歴',
                'verbose_name_plural': 'セキュリティレポート送信履歴',
                'ordering': ['-report_date'],
            },
        ),
    ]
